#!/usr/bin/env bash
#Prints Fizz, Buzz, & FizzBuzz for all multiples of 3, 5, & both 3 & 5 respectively of numbers 1 to 100
for x in {1..100}
do
    f=$((x%3))
    b=$((x%5))
    if [ $f -eq 0 ] && [ $b -eq 0 ]
    then
	echo "FizzBuzz"
    else
	if [ $b -eq 0 ]
	then
	    echo "Buzz"
	elif [ $f -eq 0 ]
	then
	    echo "Fizz"
	else
	    echo "$x"
	fi
    fi
done
