#!/usr/bin/env bash
#Write a story using data from /etc/passwd using while & without use of either for or until.
while IFS=: read -r U_N PASS U_ID G_ID UID_INFO H_DIR SHELL
do
    echo "The user $U_N is part of the $G_ID gang, lives in $H_DIR and rides $SHELL. $U_ID's place is protected by the passcode $PASS, more info about the user here: $UID_INFO"
done < /etc/passwd
