#!/usr/bin/env bash
#Write a story using data from /etc/passwd using while & without use of either for or until.
U_N=$( (cut -d: -f1) < /etc/passwd)
G_ID=$( (cut -d: -f4) < /etc/passwd)
H_DIR=$( (cut -d: -f6) < /etc/passwd)
SHELL=$( (cut -d: -f7) < /etc/passwd)
U_ID=$( (cut -d: -f3) < /etc/passwd)
PASS=$( (cut -d: -f2) < /etc/passwd)
UID_INFO=$( (cut -d: -f5) < /etc/passwd)

while IFS=: read -r U_N G_ID H_DIR SHELL U_ID PASS UID_INFO
do
    echo "The user $U_N is part of the $G_ID gang, lives in $H_DIR and rides $SHELL. $U_ID's place is protected by the passcode $PASS, more info about the user here: $UID_INFO"
done < /etc/passwd
