#!/usr/bin/env bash
#Group visitors by IP & HTTP status code from greatest to least number of occurrences - as parsed from apache-access.log
awk '{ print $1, $9 }' apache-access.log | sort | uniq -c | sort -nr
