#!/usr/bin/env bash
#Uses while without use of either for or until in order to print "Best School" 10 times with "Hi" inserted after the 9th iteration
pp=0
while [[ $pp -le 9 ]]
do
    if
	[[ $pp -eq 9 ]]
    then
	echo "Hi"
    fi
    pp=$((pp+1))
    echo -e "Best School"
done
