#!/usr/bin/env bash
#Uses while without use of either for or until in order to print "Best School" 10 times with "bad luck" and "good luck" inserted instead of the 4th and 8th iterations respectively
pp=1
while [[ $pp -le 10 ]]
do
    pp=$((pp+1))
    if [[ "$pp" -eq '5' ]]
    then
	echo -e "bad luck"
    elif [[ "$pp" -eq '9' ]]
    then
	echo -e "good luck"
    else
	echo "Best School"
    fi
done
