#!/usr/bin/env bash
#Writing a bash script that gives information about 'school' file using if and else and without use of case
ook=school
if [[ -e $ook && -s $ook ]]
then
    echo "$ook file exists" && echo "$ook file is not empty"
elif [[ -e $ook ]]
then
    echo "$ook file exists" && echo "$ook file is empty"
else
    echo "$ook file does not exist"
fi
if [[ -f $ook ]]
then
   echo "$ook is a regular file"
fi
