#!/usr/bin/env bash
#When run, export this script's PID to /var/run/myscript.pid, display toy story stuff indefinitely, defy SIGTERM, Y U no love me?! upon SIGINT, and deletes itself upon SIGQUIT or SIGTERM
pgrep 10-process_and_pid_file > /var/run/myscript.pid
toy_story=1
while [ $toy_story -ge 1 ]
do
    toy_story=$((toy_story+1))
    echo "To infinity and beyond"
    trap 'echo "I hate the kill command"' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'rm /var/run/myscript.pid' SIGQUIT SIGTERM
done
