#!/usr/bin/env bash
#This (init) script is meant to manage script file: manage_my_process
case "$1" in
    start)
	sudo bash -c manage_my_process
	pgrep manage_my_process > /var/run/my_process.pid
	echo "manage_my_process started"
	;;
    stop)
	pkill -f "manage_my_process"
	sudo rm /var/run/my_process.pid
	echo "manage_my_process stopped"
	;;
    restart)
	pkill -f "manage_my_process"
	sudo rm /var/run/my_process.pid
	sudo bash -c manage_my_process
	pgrep manage_my_process > /var/run/my_process.pid
	echo "manage_my_process restarted"
	;;
    *)
	echo "Usage: manage_my_process {start|stop|restart}"
	;;
esac
