#!/usr/bin/env bash
#This (init) script is meant to manage script file: manage_my_process
start() {
    ./manage_my_process && pgrep manage_my_process > /var/run/my_process.pid && echo "manage_my_process started"
}

stop() {
    sudo kill "$(pgrep -f ./manage_my_process)" && sudo rm "/var/run/my_process.pid" && echo "manage_my_process stopped"
}

restart() {
    stop && start && echo "manage_my_process restarted"
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
	restart
	;;
    *)
	echo "Usage: manage_my_process {start|stop|restart}"
	;;
esac
