#!/usr/bin/env bash
#This (init) script is meant to manage script file: manage_my_process
start() {
    sudo ./manage_my_process
}

stop() {
    sudo kill "$(pgrep -f manage_my_process)"
}

restart() {
    stop && start
}

case "$1" in
    start)
	start
	pgrep manage_my_process > /var/run/my_process.pid
	echo "manage_my_process started"
	;;
    stop)
	stop
	sudo /usr/bin/rm /var/run/my_process.pid
	echo "manage_my_process stopped"
	;;
    restart)
	restart
	echo "manage_my_process restarted"
	;;
    *)
	echo "Usage: manage_my_process {start|stop|restart}"
	;;
esac
